### ISSUE TITLE
Anyone please give us little bit description of this project. 

### ISSUE THREAD

**Issue by irufaan** [MaldivianDevelopers/portal#6]
I am asking this because i want save my time to read all the codes to understand the whole project. Most of the projects i worked on before they have project descriptions, functions and requirement. 
who is the project Manager?
what is the progress?
what i can contribute for this project?
Thank you

**Comment by ajaaibu** [comment]
As stated on the readme, this repository hosts the code base of developers.mv community portal. We are developing on top of https://github.com/laravelio/portal. Reason why we had to come up with something like this is well explained by @raftalks at https://developers.mv/forum/why-create-developersmv. This project is maintained by developers community of Maldives, @raftalks is the lead as of now.

Regarding progress, this is very infant and we are still on discussions on how can we further develop this to make it more resourceful for our community.

As the primary goal of this project is to strengthen the developers community of Maldives, in my opinion the greatest contribution that one could give is the active engagement in the community. It can be as simple as helping out a fellow dev who is in need. Also we really really encourage everyone to make PRs to further enhance this portal.

**Comment by irufaan** [comment]
thank you for the info..
